name: Build Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docker-compose.yml'
      - 'docker-compose-warp.yml'
      - 'docs/**'
      - '.github/workflows/build_docker_main.yml'
      - '.github/workflows/build_docker_dev.yml'
  workflow_dispatch:

env:
  REGISTRY: crpi-tyce9o8tisqe9vrd.cn-shanghai.personal.cr.aliyuncs.com
  IMAGE: crazy_david/chat2api

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-,enable=true

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Inspect image
        run: docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ steps.meta.outputs.version }}